# GitHub Action to remove expired stories from the database.

name: Remove Expired Stories

# Trigger the workflow on a push to the main branch and every 8 hours.
on:
  push:
    branches: [main] # Run the workflow when changes are pushed to the 'main' branch.
  schedule:
    - cron: "* */8 * * *" # Schedule the workflow to run every 8 hours.

jobs:
  add-document:
    # Specify the environment where the job runs.
    runs-on: ubuntu-latest # Use the latest Ubuntu environment for running this job.

    steps:
      # Step 1: Check out the repository containing the source code.
      - uses: actions/checkout@v3 # Pull the latest code from the repository.

      # Step 2: Set up Node.js for the workflow.
      - uses: actions/setup-node@v3 # Configure Node.js in the runner environment.
        with:
          node-version: "20" # Specify the Node.js version to use.

      # Step 3: Install Firebase as a dependency.
      - run: npm install firebase # Install the Firebase library to interact with Firebase services.

      # Step 4: Execute the script to remove expired stories.
      - run: node src/common/utils/expired/removeExpiredStories.mjs # Run the Node.js script to clean up expired stories.
