name: Remove inactive users

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 */4 * *" # Every 4 days at midnight

jobs:
  clean-inactive-users:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Create the Firebase service account JSON file
      - name: Create Firebase credentials file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebaseServiceAccountKey.json

      # Step 4: Install Firebase Admin SDK
      - name: Install dependencies
        run: npm install firebase-admin

      # Step 5: Run the cleanup script
      - name: Remove inactive users
        run: node src/common/utils/expired/RemoveInactiveUsers.mjs
